### ISSUE TITLE
Errors related to security context constraints

### ISSUE THREAD

**Issue by dymurray** [samarcho/BlockApps-OpenShift#1]
Hey there,

I'm trying to run this on an `oc cluster up` environment and running into trouble with the containers requiring the ability to run as any UID. Would you mind providing me with some more information around the security contexts you are working with and how I might be able to do the same? Here are some logs from just cloning the repo and running `./startup.sh foo2`:

```
[dymurray@dymurray BlockApps-OpenShift]$ oc get pods
NAME                       READY     STATUS             RESTARTS   AGE
postgres-cirrus-1-7qj28    0/1       CrashLoopBackOff   4          2m
postgres-cirrus-1-deploy   1/1       Running            0          2m
redis-1-d4ccx              0/1       CrashLoopBackOff   4          2m
redis-1-deploy             1/1       Running            0          2m
zookeeper-1-9jvjn          0/1       CrashLoopBackOff   4          2m
zookeeper-1-deploy         1/1       Running            0          2m
```

```
[dymurray@dymurray BlockApps-OpenShift]$ oc logs postgres-cirrus-1-7qj28 
initdb: could not look up effective user ID 1000080000: user does not exist
```

```
[dymurray@dymurray BlockApps-OpenShift]$ oc logs redis-1-d4ccx 
1:M 15 Oct 15:16:46.818 # Can't open the append-only file: Permission denied
```

```
[dymurray@dymurray BlockApps-OpenShift]$ oc logs zookeeper-1-9jvjn 
/docker-entrypoint.sh: line 15: /conf/zoo.cfg: Permission denied
```

I'm wondering if somehow your `developer` user is running in the privileged scc?

Any info you can provide me with would be great. Thanks!

**Comment by dymurray** [comment]
I was able to resolve the previous problems running:
`oc adm policy add-scc-to-group anyuid system:authenticated`.

Now when I run the startup script I get 3 pods running: `postgres-cirrus`, `redis`, and `zookeeper`. The rest of the my deployments are not triggered automatically and when I try to manually deploy them I get the error: 
```
error: An error occurred while starting the deployment.
 Reason: cannot trigger a deployment for "nginx" because it contains unresolved images
```

Trying to figure out why the imagestreams are not working properly for these other images.

**Comment by dymurray** [comment]
Actually, I have a better understanding now. This must be related to the secret that gets created in the startup script because all of the deployments that are failing are the images coming from `registry-aws.blockapps.net:5000`. I think this must be related to my docker login config. Sorry for spamming this issue with comments but figured it might help having a detailed explanation of the problems I run into trying to stand it up.

```
oc get is bloch -o yaml
....
status:
  dockerImageRepository: 172.30.1.1:5000/foo/bloch
  tags:
  - conditions:
    - generation: 2
      lastTransitionTime: 2017-10-16T13:15:01Z
      message: 'Internal error occurred: Get https://registry-aws.blockapps.net:5000/v2/blockapps-repo/silo-bloch/manifests/latest:
        unauthorized: authentication required'
```
